services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    profiles:
      - local

    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: sik

    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 120s

    ports:
      - "3306:3306"

  backend:
    build: ./backend
    container_name: ppa-backend

    env_file:
      - ./backend/.env

    extra_hosts:
      - "host.docker.internal:host-gateway"

    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: ppa-frontend

    depends_on:
      - backend

    ports:
      - "3000:3000"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ppa-phpmyadmin
    profiles:
      - local

    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ''
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  mysql_data: