services:

  backend:
    build: ./backend
    container_name: ppa-backend

    env_file:
      - ./backend/.env

    extra_hosts:
      - "host.docker.internal:host-gateway"

    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: ppa-frontend

    depends_on:
      - backend

    ports:
      - "3000:3000"